module.exports = {
  // normalized pairs: BASE-QUOTE
  //BTC, LTC, ETH, ETC, ZEC, XMR, DSH, XRP, OMG, BCH, NEO
  pairs: {
    USDTBTC: {base: 'USDT', counter: 'BTC', display: 'USDT-BTC'},
    USDTLTC: {base: 'USDT', counter: 'LTC', display: 'USDT-LTC'},
    USDTETH: {base: 'USDT', counter: 'ETH', display: 'USDT-ETH'},
    USDTETC: {base: 'USDT', counter: 'ETC', display: 'USDT-ETC'},
    USDTZEC: {base: 'USDT', counter: 'ZEC', display: 'USDT-ZEC'},
    USDTXMR: {base: 'USDT', counter: 'XMR', display: 'USDT-XMR'},
    USDTDSH: {base: 'USDT', counter: 'DSH', display: 'USDT-DSH'},
    USDTXRP: {base: 'USDT', counter: 'XRP', display: 'USDT-XRP'},
    USDTOMG: {base: 'USDT', counter: 'OMG', display: 'USDT-OMG'},
    USDTBCH: {base: 'USDT', counter: 'BCH', display: 'USDT-BCH'},
    USDTNEO: {base: 'USDT', counter: 'NEO', display: 'USDT-NEO'}
  },
  exchanges: {
    BITFINEX: 'BITF',
    BITTREX: 'BTRX'
  },
  sides: {
    ASK: 'ask',
    BID: 'bid',
    LONG: 'long',
    SHORT: 'short'
  },
  position: {
    SHORT: 'SHORT', LONG: 'LONG'
  },
  bitfinexSymbols: [
    'btcusd',
    'ltcusd',
    'ltcbtc',
    'ethusd',
    'ethbtc',
    'etcbtc',
    'etcusd',
    'rrtusd',
    'rrtbtc',
    'zecusd',
    'zecbtc',
    'xmrusd',
    'xmrbtc',
    'dshusd',
    'dshbtc',
    'bccbtc',
    'bcubtc',
    'bccusd',
    'bcuusd',
    'xrpusd',
    'xrpbtc',
    'iotusd',
    'iotbtc',
    'ioteth',
    'eosusd',
    'eosbtc',
    'eoseth',
    'sanusd',
    'sanbtc',
    'saneth',
    'omgusd',
    'omgbtc',
    'omgeth',
    'bchusd',
    'bchbtc',
    'bcheth',
    'neousd',
    'neobtc',
    'neoeth',
    'etpusd',
    'etpbtc',
    'etpeth',
    'qtmusd',
    'qtmbtc',
    'qtmeth',
    'bt1usd',
    'bt2usd',
    'bt1btc',
    'bt2btc',
    'avtusd',
    'avtbtc',
    'avteth'
  ]
}
